### ISSUE TITLE
Seeing warning `Several alternatives for attribute name '{key}'`

### ISSUE THREAD

**Issue by nickdos** [Rogdham/bigxml#1]
My script runs fine on a small version of my XML file but using a larger version, fails with the warning:

```python
parse_biosample_into_DB.py in Entry.handle_email(self, node)
    @xml_handle_element("Owner","Contacts","Contact")
        def handle_email(self, node):
--->     if node.attributes['email']:
                 self.email = node.attributes['email']

File /usr/local/lib/python3.9/site-packages/bigxml/nodes.py:26, in XMLElementAttributes.__getitem__(self, key)
 def __getitem__(self, key):
     alternatives, value = self._items[key]
     if alternatives > 1:
         warnings.warn(
             (
                 f"Several alternatives for attribute name '{key}'."
   (...)
             RuntimeWarning,
         )

KeyError: 'email'
```

The offending handler (inside a dataclass):

```python
    @xml_handle_element("Owner","Contacts","Contact")
    def handle_email(self, node):
        if node.attributes['email']:
            self.email = node.attributes['email']
```

The data looks like:

```xml
<Contact email="foo@bar.com"/>
```

but there are a few instances of

```xml
<Contact email="foo@bar.com" lab="ACME Labs">
    <Name>
        <First>Jane</First>
        <Last>Doe</Last>
    </Name>
</Contact>
```

I can't see any other elements with the attribute `email` in my XML file, so I'm lost as to why this is occurring.

**Comment by nickdos** [comment]
Disregard - I discovered some nodes do not have the `email` attribute, so I solved the issue with:

```python
    if node.attributes.get('email'):
```

**Comment by Rogdham** [comment]
#### About the `Several alternatives for attribute name` warning

This warning occurs that there are several attributes with different namespaces, so we don't know which value to get. [More info in the docs](https://bigxml.rogdham.net/namespaces/#namespaced-attributes).

I don't think that's the case here however, since you don't get the warning but only sees it in the stacktrace to provide context.


#### The `KeyError` exception

The exception you are having is `KeyError: 'email'`.

Maybe there are some `Contact` tag without the `email` attribute?

In which case, you could do for example:

```py
if 'email' in node.attributes:
    self.email = node.attributes['email']
```

or with a walrus operator:

```py
if email := node.attributes.get('email'):
    self.email = email
```
