### ISSUE TITLE
Unable to ignore "Not well-formed (invalid token)"

### ISSUE THREAD

**Issue by Fissium** [Rogdham/bigxml#8]
Hi there! Firstly, thanks for maintaining such an excellent library!

I've encountered an issue while parsing an XML file using the `requests` library. Despite ensuring the correct encoding, I'm consistently met with the error message: `Not well-formed (invalid token): line 5270716, column 155`.

Is there a way to implement a mechanism within the library to allow the parsing process to ignore such errors and continue parsing the rest of the XML file?

**Comment by Rogdham** [comment]
Hello, your error message tells us that the XML data you are passing to `Parser` is not valid XML. For example, I was able to reproduce with the following data (notice the value of `attrib`):

```xml
<root>
    <element attrib="<">foo</element>
</root>
```

Unfortunately, I don't know of a way to just ignore the problem. We are not out of solutions yet however, and I suggest trying to see what your invalid XML line is.

Could you dump the full response into a file and send it here (at least the line in error)? For example with something like the following (creating a file named `dump.xml`):
```python
response = requests.get("https://example.com/placeholder.xml", stream=True)

with open('dump.xml', 'wb') as f:
    for data in response.iter_content(None):
        f.write(data)
```

An other idea would be to dump only the line causing the error, for example with something like this:
```python
def raise_on_line(iterable, target_lineno):
    lineno, buffer = 1, b""
    for data in iterable:
        buffer += data
        for line in buffer.split(b"\n"):
            if lineno == target_lineno:
                raise ValueError(line)
            lineno += 1


response = requests.get("https://example.com/placeholder.xml", stream=True)

raise_on_line(
    response.iter_content(None),
    5270716  # your line having the error
)
```

This would help figuring out what the issue is exactly. Thanks!

**Comment by Fissium** [comment]
Hello,

Thank you for your prompt response and suggestions.

I've followed your guidance and isolated the line causing the issue. It appears to be:

`ValueError: b'\t\t<available>false</available>\r'`

**Comment by Rogdham** [comment]
Thank you for the followup. However the line you provided does not seem to be the right one. I suspect the HTTP response changed from your first message, so the line number in my code is not right anymore. We can see that also because your provided line has less than 155 characters.

So we need to be a little smarter about getting the line in error. Could you use the following code? The idea is to wrap the response of the HTTP server so that we are able to keep the last 5 lines.

```python
from bigxml import Parser, BigXmlError


# change the following line according to your HTTP call

response = requests.get("https://example.com/placeholder.xml", stream=True)


# you don't need to change anything below

class Wrapped:
    def __init__(self, iterable):
        self.iterable = iterable
        self.buffer = b""
        self.last_lines = []
        self.lineno = 0

    def __iter__(self):
        return self

    def __next__(self):
        while b"\n" not in self.buffer:
            self.buffer += next(self.iterable)
        last_line, self.buffer = self.buffer.split(b"\n", 1)
        last_line += b"\n"
        self.lineno += 1
        self.last_lines.append(last_line)
        self.last_lines = self.last_lines[-5:]  # keep only last 5 lines
        return last_line


wrapped = Wrapped(response.iter_content(None))

try:
    Parser(wrapped).return_from()
except BigXmlError as ex:
    print(wrapped.lineno, wrapped.last_lines)
    print(ex)
```

**Comment by Fissium** [comment]
Now the output is as follows:
```
5270350 [b"\t\t<param name='\xd0\xa6\xd0\xb2\xd0\xb5\xd1\x82'>\xd0\xbf\xd0\xb0\xd1\x82\xd0\xb8\xd0\xbd\xd0\xb0</param>\r\n", b"\t\t<param name='addedDate'>2014-01-26</param>\r\n", b'\t</offer>\r\n', b"\t<offer id='80094645' available='false' group_id='167957'>\r\n"]
Not well-formed (invalid token): line 5270350, column 155
```

**Comment by Rogdham** [comment]
There is something I don't understand here: we have the right line number, but the line is less than 155 bytes. Plus, I tried to recreate an XML file including the data from your last message, and there was no issue to parse it.

Would it be possible to send me the full response from the HTTP server? By using this code snippet to save the output to a local file named `dump.xml`:
```py
# change the following line according to your HTTP call
response = requests.get("https://example.com/placeholder.xml", stream=True)

with open('dump.xml', 'wb') as f:
    for data in response.iter_content(None):
        f.write(data)
```

You can use  [wetransfer.com](https://wetransfer.com/) or [swisstransfer.com](https://www.swisstransfer.com/) to upload the file and generate a download link. Feel free to compress it before if you want, or encrypt with [my GPG key](https://keys.openpgp.org/vks/v1/by-fingerprint/49E7F2124F8A7154540F79973586E588AEF1642D) for confidentiality purposes.

**Comment by Fissium** [comment]
Here is the link to the compressed dump https://www.swisstransfer.com/d/2e18f606-767a-49ef-934e-aa5e84e13fde

**Comment by Rogdham** [comment]
Thank you for the dump! The line having the issue is the following:
```xml
<url>https://...redacted.../reproduktsiya_30x40_sm_pink_flowers_&_grey_stones_id167957/?articul=80094645</url>
```

The issue is that the `&` in the URL should be encoded into `&amp;`, otherwise it's not valid XML.

I suggest the following workaround:
```py
def fix_amp(iterable):
    iterator = iter(iterable)
    for data in iterator:
        while data.endswith(b"&"):
            data += next(iterator)
        yield data.replace(b"&_", b"&amp;_")  # feel free to improve with a regex, etc.
```

Then when you call `Parser`, instead of `Parser(response.iter_content(None))`, do `Parser(fix_amp(response.iter_content(None)))`.

Tell me if that works for you!

**Comment by Fissium** [comment]
Yes, it works! Thank you very much!
